oe2403lts:
  target_os_version:
    - 24.03
    - LTS
  target_sys_version: openEuler24.03-LTS
  repo_name: migrate-oe2403lts.repo

oe2403sp1:
  target_os_version:
    - 24.03
    - LTS-SP1
  target_sys_version: openEuler24.03-LTS-SP1
  repo_name: migrate-oe2403sp1.repo

oe2203sp1:
  target_os_version:
    - 22.03
    - LTS-SP1
  target_sys_version: openEuler22.03-LTS-SP1
  repo_name: migrate-oe2203sp1.repo

oe2203sp3:
  target_os_version:
    - 22.03
    - LTS-SP3
  target_sys_version: openEuler22.03-LTS-SP3
  repo_name: migrate-oe2203sp3.repo

oe2203sp4:
  target_os_version:
    - 22.03
    - LTS-SP4
  target_sys_version: openEuler22.03-LTS-SP4
  repo_name: migrate-oe2203sp4.repo

oe2003sp4:
  target_os_version:
    - 20.03
    - LTS-SP4
  target_sys_version: openEuler20.03-LTS-SP4
  repo_name: migrate-oe2003sp4.repo