#收集主机配置文件信息
- case_name: 收集主机的单个配置文件信息
  data:
    infos:
      - host_id: $host_id
        config_list:
          - /etc/aops/system.ini
  validate:
    code: 200
    data:
      - fail_files: [ ]
        host_id: $host_id
        infos:
          - content: log module
            file_attr:
              group: root
              mode: 0644
              owner: root
            path: /etc/aops/system.ini
        success_files:
          - /etc/aops/system.ini
    label: Succeed
    message: operation succeed

- case_name: 收集主机不存在的文件信息
  data:
    infos:
      - host_id: $host_id
        config_list:
          - non-exist-file
  validate:
    code: 200
    data:
      - fail_files:
          - non-exist-file
        host_id: $host_id
        infos: [ ]
        success_files: [ ]
    label: Succeed
    message: operation succeed

- case_name: 收集主机配置文件信息-config_list为空
  data:
    infos:
      - host_id: $host_id
        config_list: [ ]
  validate:
    code: 1000
    label: Param.Error
    message: request parameter error

- case_name: 收集主机配置文件信息-host_id为空
  data:
    infos:
      - host_id: None
        config_list:
          - /etc/aops/system.ini
  validate:
    code: 1000
    label: Param.Error
    message: request parameter error

- case_name: 收集主机配置文件信息-host_id错误
  data:
    infos:
      - host_id: qwer
        config_list:
          - /etc/aops/system.ini
  validate:
    code: 1000
    label: Param.Error
    message: request parameter error