#!/bin/bash
# Copyright (c) 2023. Huawei Technologies Co.,Ltd.ALL rights reserved.
# This program is licensed under Mulan PSL v2.
# You can use it according to the terms and conditions of the Mulan PSL v2.
#          http://license.coscl.org.cn/MulanPSL2
# THIS PROGRAM IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.

# #############################################
# @Author    :   hekeming
# @Contact   :   hk16897@126.com
# @Date      :   2023/07/03
# @License   :   Mulan PSL v2
# @Desc      :   Test SSH link
# ############################################
############################# 工具下载相关配置项 ##################################################

# arch arm or x86
arch=x86

# remote tools factory
download_url=http://90.90.61.222/Bigdata

# TPCDS config items
tpcds_package=TPC-DS-x86_64.tar.gz
tpcds_extract_dir=TPC-DS-x86_64
#tpcds_package=TPC-DS-x86_64.tar.gz
#tpcds_extract_dir=TPC-DS-x86_64

# Hibench config items
hibench_package=HiBench-HiBench-7.0.tar.gz
hibench_extract_dir=HiBench-HiBench-8.0

# Benchmark config items
benchmark_package=yahoo-streaming-benchmark.tar.gz
benchmark_extract_dir=yahoo-streaming-benchmark

# EsDeps config items
esdeps_package=esDepsTools.tar.gz
esdeps_extract_dir=esDepsTools




############################# 集群环境相关配置项 ##################################################

# cluster ip array
#clusterip=xxx.xxx.xxx.xxx,xxx.xxx.xxx.xxx,xxx.xxx.xxx.xxx,xxx.xxx.xxx.xxx
clusterip=server1,agent1,agent2,agent3
# cluster root password
# clusterpasswd=Huawei12#$
